---
title: "Procedures of meta-analysis"
author: ""
date: "`r Sys.Date()`"
output: 
  word_document: 
    toc: true
    toc_depth: 3
  pdf_document:
    toc: true
    toc_depth: 3
    latex_engine: xelatex
---

# Loading necessary libraries

```{r}
library(openxlsx)
library(meta)
library(robvis)
library(robumeta)
library(metapower)
library(metafor)
```

# Visualising risk of bias

First, we load the RoB data with the following code:

```{r}
pdf('RoB_summary.pdf')
RoB_data <- unique(read.xlsx("RoB_summary.xlsx"))
rob_traffic <- rob_traffic_light(data = RoB_data, tool = "ROB2", psize = 5)
rob_traffic
dev.off()
```

```{r}
pdf('RoB_summary2.pdf', width = 7, height = 4)
RoB_data <- unique(read.xlsx("RoB_summary.xlsx"))
rob_barplot <- rob_summary(data = RoB_data, tool = "ROB2", psize = 5, weighted = FALSE)
rob_barplot
dev.off()
```

```{r}
caregiver_burden_data <- read.xlsx("caregiver_burden_subset.xlsx")
median(as.numeric(caregiver_burden_data$"Post-study_N"))
mean(median(as.numeric(caregiver_burden_data$"Post-study_N")))
```


```{r}
power_analysis <- mpower(effect_size = 1, k = 33, study_size = 26, i2 = 0.9, es_type = 'd')
power_analysis

pdf('power_analysis.pdf')
plot_mpower(power_analysis)
dev.off()
```

```{r}
colnames(caregiver_burden_data)
```

```{r}
caregiver_burden_data <- read.xlsx("caregiver_burden_subset.xlsx", "Sheet2")
caregiver_burden_data_control <-  caregiver_burden_data[caregiver_burden_data$'Control?' == 'Y',]
caregiver_burden_data_event <- caregiver_burden_data[caregiver_burden_data$'Control?' == 'N',]
```



```{r}
caregiver_burden_data_control$'Event_Baseline' <-  caregiver_burden_data_event$'Baseline'
caregiver_burden_data_control$'Event_Baseline_N' <-  caregiver_burden_data_event$'Baseline_N'
caregiver_burden_data_control$'Event_Baseline_SD' <-  caregiver_burden_data_event$'Baseline_SD'
caregiver_burden_data_control$'Event_Post-study' <-  caregiver_burden_data_event$'Post-study'
caregiver_burden_data_control$'Event_Post-study_N' <-  caregiver_burden_data_event$'Post-study_N'
caregiver_burden_data_control$'Event_Post-study_SD' <-  caregiver_burden_data_event$'Post-study_SD'
```


```{r}
caregiver_burden_data$Baseline_N <- as.numeric(caregiver_burden_data$Baseline_N)
caregiver_burden_data$Baseline <- as.numeric(caregiver_burden_data$Baseline)
caregiver_burden_data$Baseline_SD <- as.numeric(caregiver_burden_data$Baseline_SD)
caregiver_burden_data$'Post-study_N' <- as.numeric(caregiver_burden_data$'Post-study_N')
caregiver_burden_data$'Post-study' <- as.numeric(caregiver_burden_data$'Post-study')
caregiver_burden_data$'Post-study_SD' <- as.numeric(caregiver_burden_data$'Post-study_SD')
caregiver_burden_data_control
```


```{r}
meta1 <- metacont(
  n.c = as.numeric(caregiver_burden_data_control$'Baseline_N'),
  mean.c = as.numeric(caregiver_burden_data_control$'Baseline'),
  sd.c = as.numeric(caregiver_burden_data_control$'Baseline_SD'),
  n.e = as.numeric(caregiver_burden_data_control$'Post-study_N'),
  mean.e = as.numeric(caregiver_burden_data_control$'Post-study'),
  sd.e = as.numeric(caregiver_burden_data_control$'Post-study_SD'),
  studlab = caregiver_burden_data_control$'Study.Identifier')
meta1
```

```{r}
pdf('meta1.pdf', width = 18, height = 10)
forest(meta1, prediction = TRUE)
dev.off()
```

```{r}
meta2 <- metacont(
  n.c = as.numeric(caregiver_burden_data_control$'Event_Baseline_N'),
  mean.c = as.numeric(caregiver_burden_data_control$'Event_Baseline'),
  sd.c = as.numeric(caregiver_burden_data_control$'Event_Baseline_SD'),
  n.e = as.numeric(caregiver_burden_data_control$'Event_Post-study_N'),
  mean.e = as.numeric(caregiver_burden_data_control$'Event_Post-study'),
  sd.e = as.numeric(caregiver_burden_data_control$'Event_Post-study_SD'),
  studlab = caregiver_burden_data_control$'Study.Identifier', sm = "SMD", method.smd = "Cohen", random = TRUE, common = FALSE)
meta2
```

```{r}
pdf('meta2.pdf', width = 18, height = 10)
forest(meta2, prediction = TRUE)
dev.off()

pdf('meta2-funnel.pdf', width = 18, height = 10)
funnel(meta2)
dev.off()

```